pipeline{

  agent any

   environment{
   NUMBER = 3
   }

  stages{

         stage('stage-1'){
               steps{

                  echo "docker run -e NUMBER=${NUMBER} manojmathpal/squares"


               }


         }

         stage('stage-2'){
         environment {
          NUMBER = 6
         }

         steps{
                  echo "docker run -e NUMBER=${NUMBER} manojmathpal/squares"

         }



         }


         stage('stage-3'){
            steps{
             echo "docker run -e NUMBER=${NUMBER} manojmathpal/squares"
            }

         }





  }



   post{
   always{
        echo "docker system prune -f"
   }

   }







}